language: c
compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libtool gtk-doc-tools libdbus-1-dev uuid-dev
  - sudo apt-get install pkg-config automake autotools-dev autopoint
  - git clone https://github.com/GNOME/glib.git
  - cd glib && ./configure --prefix /usr/local && make && sudo make install && cd
  - git clone https://github.com/thom311/libnl.git
  - cd libnl && ./configure --prefix /usr/local && make && sudo make install && cd

script: ./autogen.sh && make
